on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Context
        uses: okteto/context@latest
        with:
          url: ${{secrets.OKTETO_URL}}
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ifbyol-${{ github.event.number }}-pr
          timeout: 15m
          scope: global
          variables: OKTETO_PR_NUMBER=${{ github.event.number }},OKTETO_PR_COMMIT=${{ github.sha }}